// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlXRpO_u0-FaZR9STYkJwZHFqMEGfxvic',
    appId: '1:541067722545:web:eee06f34e18c158980fa10',
    messagingSenderId: '541067722545',
    projectId: 'cryptocoins-5b91f',
    authDomain: 'cryptocoins-5b91f.firebaseapp.com',
    databaseURL: 'https://cryptocoins-5b91f-default-rtdb.firebaseio.com',
    storageBucket: 'cryptocoins-5b91f.appspot.com',
    measurementId: 'G-PVJ0ZHYNJ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCognpyrdnCu1snURjFd_rj--qvzjal3qc',
    appId: '1:541067722545:android:218174ffd01c019f80fa10',
    messagingSenderId: '541067722545',
    projectId: 'cryptocoins-5b91f',
    databaseURL: 'https://cryptocoins-5b91f-default-rtdb.firebaseio.com',
    storageBucket: 'cryptocoins-5b91f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC502ML5VaEthEdvptkfu8VFTb12e1CxpI',
    appId: '1:541067722545:ios:0e2974521738dba780fa10',
    messagingSenderId: '541067722545',
    projectId: 'cryptocoins-5b91f',
    databaseURL: 'https://cryptocoins-5b91f-default-rtdb.firebaseio.com',
    storageBucket: 'cryptocoins-5b91f.appspot.com',
    iosClientId: '541067722545-d7p5g31m3l3hblrblrs0sci5462lhfqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptocoins',
  );
}
